nodeLinker: node-modules

logFilters:
  # Silence warnings about incompatible architectures (like from `esbuild`)
  - code: YN0076
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
